version: "3.1"
services:
  database:
    image: quay.io/azavea/postgis:3-postgres12.4-slim
    environment:
      - POSTGRES_DB=vegishphilly
      - POSTGRES_PASSWORD=vegishphilly
      - POSTGRES_USER=vegishphilly
    healthcheck:
      test: pg_isready -U vegishphilly
      interval: 3s
      timeout: 3s
      retries: 3

  django:
    image: vegishphilly
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vegishphilly
      - POSTGRES_PASSWORD=vegishphilly
      - POSTGRES_DB=vegishphilly
      - DJANGO_SECRET_KEY=secret
      - VEGISHPHILLY_APP_HOME=${VEGISHPHILLY_APP_HOME:-http://localhost:3033}
    build:
      context: ./django
      dockerfile: Dockerfile
    volumes:
      - ./django:/usr/local/src/django
    working_dir: /usr/local/src/django
    ports:
      - "8033:8033"
    depends_on:
      database:
        condition: service_healthy
    command:
      - "-b :8033"
      - "--reload"
      - "--access-logfile=-"
      - "--error-logfile=-"
      - "--log-level=info"
      - "vegishphilly.wsgi"

  client:
    image: node:12-slim
    stdin_open: true
    environment:
      - PORT=4567
    volumes:
      - ./client:/usr/local/src/client
      - ./django/static:/usr/local/src/client/build
       # Ensure node_modules cache doesn't clash with other jobs on CI.
      - /var/cache/vegishphilly-client-node-modules:/usr/local/src/client/node_modules
      - $HOME/.cache/vegishphilly:/usr/local/share/.cache/yarn
    working_dir: /usr/local/src/client
    ports: 
      - "4567:4567"
    command: yarn start

  shellcheck:
    image: koalaman/shellcheck:stable
    volumes:
      - ./:/usr/local/src
    working_dir: /usr/local/src

volumes:
  pgdata:
