# Generated by Django 3.2.4 on 2021-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20210812_1235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four"), (5, "Five")]
            ),
        ),
    ]
