#!/bin/bash

set -e

if [[ -n "${vegishphilly_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Build application for staging or a release.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        #Update dependencies
        echo "Updating frontend dependencies"
        docker-compose \
            run --rm client \
            yarn install

        ./scripts/lint
        ./scripts/test
    fi
fi
