#!/bin/bash

set -e

if [[ -n "${vegishphilly_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Run linters on the project's code
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint Bash scripts
        docker-compose \
            run --rm --no-deps shellcheck \
            scripts/*

        # Lint JavaScript
        docker-compose \
            run --rm --entrypoint ./node_modules/.bin/eslint \
            app src/ --ext .js --ext .jsx
        
        # Check format of Django application source code
        docker-compose \
            run --rm --no-deps --entrypoint black django \
            --check --diff .

        # Lint Django application source code
        docker-compose \
            run --rm --no-deps --entrypoint flake8 django \
            --exclude settings.py,manage.py,*.pyc,api/migrations/*
    fi
fi
