#!/bin/bash

set -e

if [[ -n "${vegishphilly_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run tests.
"
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
    if [[ "${1:-}" = "--help" ]]; then
        usage
    else
        echo "Compiling frontend source code"
        # NOTE: This is necessary because tests can pass with TS code that
        # doesn't compile
        docker-compose \
            run --rm --no-deps -e CI client \
            yarn run compile

        # Execute React test suite
        echo "Executing frontend test suite"
        docker-compose \
            run --rm --no-deps -e CI client \
            yarn run test --watchAll=false

        # Execute Django test suite
        ./scripts/manage test
    fi
fi
