#!/bin/bash

set -e

if [[ -n "${vegishphilly_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Build container images.
"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Ensure container images are current
        docker-compose build

        # Update Yarn dependencies
        docker-compose \
            run --rm --no-deps client \
            yarn install

        # Bring up PostgreSQL and Django in a way that respects
        # configured service health checks.
        docker-compose \
                -f docker-compose.yml \
                up -d database

        # Apply any outstanding Django migrations
        ./scripts/manage migrate --noinput

        # Collect Django static files
        ./scripts/manage collectstatic --noinput

        docker-compose \
                -f docker-compose.yml \
                stop
    fi
fi
